# Admittance parameters for mass damper systems 

mass_matrix: [6,0,0,0,0,0,
              0,6,0,0,0,0,
              0,0,6,0,0,0,
              0,0,0,2,0,0,
              0,0,0,0,2,0,
              0,0,0,0,0,2]

damping_matrix: [40,0,0,0,0,0,
                 0,40,0,0,0,0,
                 0,0,40,0,0,0,
                 0,0,0,15,0,0,
                 0,0,0,0,15,0,
                 0,0,0,0,0,15]

# this will limit the workspace ([x_min x_max y_min y_max z_min z_max])
# This is in the world reference frame!! Might need to change to arm_base_link
workspace_limits: [0.45, 1.5, -1.3, 1.3, 0.10, 1.4]
maximum_velocity: 0.2
maximum_acceleration: 0.2
