# Admittance parameters for mass damper systems 

# mass_matrix: [6,0,0,0,0,0,
#               0,6,0,0,0,0,
#               0,0,6,0,0,0,
#               0,0,0,2,0,0,
#               0,0,0,0,2,0,
#               0,0,0,0,0,2]

# damping_matrix: [40,0,0,0,0,0,
#                  0,40,0,0,0,0,
#                  0,0,40,0,0,0,
#                  0,0,0,15,0,0,
#                  0,0,0,0,15,0,
#                  0,0,0,0,0,15]

# mass_matrix: [1.5,0,0,0,0,0,
#               0,1.5,0,0,0,0,
#               0,0,1.5,0,0,0,
#               0,0,0,0.5,0,0,
#               0,0,0,0,0.5,0,
#               0,0,0,0,0,0.5]

# damping_matrix: [0.1,0,0,0,0,0,
#                  0,0.1,0,0,0,0,
#                  0,0,0.1,0,0,0,
#                  0,0,0,0.05,0,0,
#                  0,0,0,0,0.05,0,
#                  0,0,0,0,0,0.05]

mass_matrix: [0.75,0,0,0,0,0,
              0,0.75,0,0,0,0,
              0,0,0.75,0,0,0,
              0,0,0,0.25,0,0,
              0,0,0,0,0.25,0,
              0,0,0,0,0,0.25]

damping_matrix: [0.05,0,0,0,0,0,
                 0,0.05,0,0,0,0,
                 0,0,0.05,0,0,0,
                 0,0,0,0.025,0,0,
                 0,0,0,0,0.025,0,
                 0,0,0,0,0,0.025]

# this will limit the workspace ([x_min x_max y_min y_max z_min z_max])
workspace_limits: [0.45, 1.5, -1.3, 1.3, 0.10, 1.4]

# joint limit equal to 2*pi
joint_limits: [6.283, 6.283, 6.283, 6.283, 6.283, 6.283]

# kinematics manipulator limits
maximum_velocity: [1.05, 1.05, 1.57, 1.57, 1.57, 1.57]
maximum_acceleration: [2.61, 2.61, 2.61, 2.61, 2.61, 2.61]

# force sensor dead zone
force_dead_zone: 3.0
torque_dead_zone: 3.0

# admittance control weight
admittance_weight: 1.0
